// AUTO-GENERATED by build.ts — do not edit

import type { ProgramManifest } from '../../cornerstone/types'

export const manifests: ProgramManifest[] = 
[
  {
    "name": "Account",
    "slug": "account",
    "icon": "user-fill",
    "description": "View and edit Crown profile, recovery phrase, and danger zone",
    "entry": "./Account.tsx",
    "court": [
      "chamberlain"
    ],
    "packages": [
      "ui"
    ],
    "dock": {
      "position": 0,
      "section": "system"
    },
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Court Test",
    "slug": "court-test",
    "icon": "shield-check-fill",
    "description": "Diagnostic — exercises every courtier in the castle",
    "entry": "./CourtTest.tsx",
    "court": [
      "chamberlain",
      "keeper",
      "castellan",
      "clerk",
      "bard",
      "artificer",
      "envoy",
      "sage",
      "magistrate",
      "tribune",
      "warden",
      "marshal",
      "treasurer",
      "interpreter",
      "tailor",
      "ambassador",
      "chronicler",
      "mentor",
      "champion",
      "scout",
      "watchman",
      "ranger"
    ],
    "packages": [
      "ui"
    ],
    "diagnostic": true,
    "dock": {
      "position": 15,
      "section": "diagnostic"
    },
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Crown Setup",
    "slug": "crown-setup",
    "icon": "shield-keyhole-fill",
    "description": "Identity creation wizard — generate a new Crown keypair",
    "entry": "./CrownSetup.tsx",
    "court": [
      "chamberlain"
    ],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Crown Unlock",
    "slug": "crown-unlock",
    "icon": "lock-unlock-fill",
    "description": "Unlock an existing Crown identity with master password",
    "entry": "./CrownUnlock.tsx",
    "court": [
      "chamberlain"
    ],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "DevTools",
    "slug": "devtools",
    "icon": "code-s-slash-fill",
    "description": "Developer tools — daemon status, pipeline tester, event log",
    "entry": "./DevTools.tsx",
    "court": [
      "daemon"
    ],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Editor Test",
    "slug": "editor-test",
    "icon": "edit-2-fill",
    "description": "Diagnostic — TipTap editor isolation test",
    "entry": "./EditorTest.tsx",
    "court": [
      "artificer"
    ],
    "packages": [
      "ui",
      "editor"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Engine Test",
    "slug": "engine-test",
    "icon": "terminal-box-fill",
    "description": "Diagnostic — browser engine capabilities and API support tests",
    "entry": "./EngineTest.tsx",
    "court": [],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Glass Test",
    "slug": "glass-test",
    "icon": "landscape-fill",
    "description": "Diagnostic — CSS glass and Crystal WebGPU rendering tests",
    "entry": "./GlassTest.tsx",
    "court": [],
    "packages": [
      "ui",
      "crystal"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Gleam Lab",
    "slug": "gleam-lab",
    "icon": "magic-fill",
    "description": "Diagnostic — interactive glass effects and material experiments",
    "entry": "./GleamLab.tsx",
    "court": [],
    "packages": [
      "ui",
      "crystal"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Home",
    "slug": "home",
    "icon": "home-4-fill",
    "description": "Landing page — identity greeting, status, and quick actions",
    "entry": "./Home.tsx",
    "court": [
      "chamberlain",
      "daemon",
      "bard",
      "envoy"
    ],
    "packages": [
      "ui"
    ],
    "dock": {
      "position": 0,
      "section": "home"
    },
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Settings",
    "slug": "settings",
    "icon": "settings-3-fill",
    "description": "Daemon configuration — network, tower, storage, and system",
    "entry": "./Settings.tsx",
    "court": [
      "config",
      "daemon",
      "castellan",
      "chamberlain",
      "envoy",
      "watchman"
    ],
    "packages": [
      "ui"
    ],
    "dock": {
      "position": 1,
      "section": "system"
    },
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "Tome",
    "slug": "tome",
    "icon": "quill-pen-fill",
    "description": "Note editor — create, edit, and share .idea documents",
    "entry": "./Tome.tsx",
    "court": [
      "chamberlain",
      "castellan",
      "clerk",
      "bard",
      "artificer",
      "vizier"
    ],
    "packages": [
      "ui",
      "editor"
    ],
    "dock": {
      "position": 2,
      "section": "home"
    },
    "intents": {
      "sends": [
        "share-content",
        "edit-content"
      ],
      "receives": [
        "edit-content"
      ]
    }
  },
  {
    "name": "UI Showcase",
    "slug": "ui-showcase",
    "icon": "palette-fill",
    "description": "Diagnostic — @omnidea/ui component gallery and design token viewer",
    "entry": "./UIShowcase.tsx",
    "court": [],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  },
  {
    "name": "WebGPU Test",
    "slug": "webgpu-test",
    "icon": "cpu-fill",
    "description": "Diagnostic — WebGPU adapter, device, and shader compilation tests",
    "entry": "./WebGPUTest.tsx",
    "court": [],
    "packages": [
      "ui"
    ],
    "intents": {
      "sends": [],
      "receives": []
    }
  }
]
