/**
 * The Orb — the sovereign's typed dominion over the protocol.
 *
 * Crown, Sceptor, Orb — the three symbols of sovereignty.
 * The Crown is identity. The Sceptor is the switchboard. The Orb is typed dominion.
 *
 * Auto-generated by orb/sync.ts from the @omnidea/net SDK.
 * Run `npx tsx orb/sync.ts` to regenerate after SDK changes.
 */

export type {
  CourtBridge,
  CourtierName,
  CourtierMap,
  TypedCastleRuntime,
} from './generated/registry.js'

export { courtierFactories } from './generated/registry.js'
export { empower } from './empower'

// Re-export all typed courtier interfaces
export type {
  AmbassadorCourt,
  ArtificerCourt,
  BardCourt,
  CastellanCourt,
  ChamberlainCourt,
  ChampionCourt,
  ChroniclerCourt,
  ClerkCourt,
  EnvoyCourt,
  InterpreterCourt,
  KeeperCourt,
  MagistrateCourt,
  MarshalCourt,
  MentorCourt,
  RangerCourt,
  SageCourt,
  ScoutCourt,
  TailorCourt,
  TreasurerCourt,
  TribuneCourt,
  WardenCourt,
  WatchmanCourt,
} from './generated/interfaces.js'
